CREATE TABLE member
(
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(30) NULL,
    city      VARCHAR(30) NULL,
    street    VARCHAR(30) NULL,
    zipcode   VARCHAR(30) NULL,
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);